version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
    - checkout
    - run:
        name: Running tests
        command: |
          virtualenv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r section6/regression_model/requirements.txt
          chmod +x ./scripts/fetch_kaggle_dataset.sh
          ./scripts/fetch_kaggle_dataset.sh
          py.test -vv section6/regression_model/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model